# Generated by Django 3.2.6 on 2021-12-29 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Creator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='ник')),
                ('is_active', models.BooleanField(default=True, verbose_name='активный')),
                ('inban', models.BooleanField(default=False, verbose_name='в бане')),
                ('data', models.TimeField(auto_now_add=True, verbose_name='дата создания')),
            ],
        ),
        migrations.CreateModel(
            name='post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('text', models.TextField(verbose_name='текст поста')),
                ('data', models.DateField(auto_now_add=True, verbose_name='Дата')),
                ('image', models.ImageField(default='NONE', upload_to='images', verbose_name='Картинка1')),
                ('type_ch', models.CharField(choices=[('Общество', 'Общество'), ('Политика', 'Политика'), ('Наука', 'Наука'), ('Экономика', 'Экономика'), ('', '')], default='', max_length=10, verbose_name='Тип новости')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tapes.creator', verbose_name='Создатель')),
            ],
        ),
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=255, verbose_name='ник пользователя')),
                ('date', models.DateField(auto_now_add=True, verbose_name='дата создания')),
                ('text', models.TextField(verbose_name='текст комментария')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tapes.post', verbose_name='родительский пост')),
            ],
        ),
    ]
